server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql:///news_release?useUnicode=true&characterEncoding=utf8
    username: root
    password: "your password"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.uml.pojo
  configuration:
    map-underscore-to-camel-case: true
    # mp设置标准输出日志，调试的时候开，上线的时候关
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.uml.mapper: info
